name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configure Web Support
        run: flutter create . --platforms web # ఇది మిస్ అయిన వెబ్ ఫోల్డర్‌ను క్రియేట్ చేస్తుంది

      - name: Build Web
        run: |
          flutter pub get
          # ఇక్కడ YOUR_REPO_NAME తీసేసి మీ రిపోజిటరీ పేరు రాయండి (ఉదా: gospel_app)
          flutter build web --release --base-href /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages